---
- name: checking for agent install
  stat:
    path: /etc/init.d/besclient
  register: agent

- debug:
    msg: "bigfix agent not found (installing)"
  when: not agent.stat.exists

- debug:
    msg: "bigfix agent found (skipping install)"
  when: agent.stat.exists

- name: create {{ redhat_bigfix_agent_path }} directory
  file:
    path: '{{ redhat_bigfix_agent_path }}'
    recurse: yes
    state: directory
    mode: 0500
  when: not agent.stat.exists

- name: install bigfix agent (redhat)
  yum:
    name: '{{ redhat_bigfix_agent_url }}'
    state: present
    validate_certs: no
    disable_plugin: "yum-rhn-plugin"
    disablerepo: "*"
    download_dir: '{{ redhat_bigfix_agent_path }}'
  when: not agent.stat.exists

- name: copy actionsite.afxm to {{ redhat_bigfix_agent_path }} directory
  get_url:
    url: '{{ bigfix_actionsite_url }}'
    dest: '{{ redhat_bigfix_agent_path }}/actionsite.afxm'
    validate_certs: no
    mode: '0755'
  when: not agent.stat.exists

- name: verify bigfix started
  service:
    name: besclient
    enabled: yes
    state: started

- name: update besclient.config for bigfix custom properties
  lineinfile:
    path: /var/opt/BESClient/besclient.config
    create: yes
    backup: yes
    insertafter: EOF
    mode: 0644
    line: |
      [Software\BigFix\EnterpriseClient\Settings\Client\{{ item.name }}]
      value                          = {{ item.value }}
      effective date                 = Thu,%2020%20Aug%202020%2010:17:38%20-0500

  with_items:
    - "{{ bigfix_custom_properties }}"
  when: not agent.stat.exists
