---
- name: create {{ redhat_agent_path }} directory
  file:
    path: '{{ redhat_agent_path }}'
    recurse: yes
    state: directory
    mode: '0755'

- name: copy actionsite.afxm to {{ redhat_agent_path }} directory
  get_url:
    url: '{{ bigfix_actionsite_url }}'
    dest: '{{ redhat_agent_path }}/actionsite.afxm'
    mode: '0755'

- name: install bigfix agent (redhat)
  yum:
    name: '{{ redhat_bigfix_agent_url }}'
    state: present

- name: start bigfix agent
  command: "/etc/init.d/besclient start"
