---
- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    recurse: yes
    state: directory

- name: install bigfix agent (windows)
  win_package:
    path: '{{ windows_bigfix_agent_url }}'
    log_path: '{{ windows_agent_log }}\\bigfix_log.txt'
    product_id: '{{ windows_bigfix_product_id }}'
    validate_certs: no
    state: present
    arguments: /qn

- name: create {{ windows_agent_path }} directory
  win_file:
    path: '{{ windows_agent_path }}'
    recurse: yes
    state: directory

- name: copy actionsite.afxm to {{ windows_agent_path }} directory
  win_get_url:
    url: '{{ bigfix_actionsite_url }}'
    dest: '{{ windows_agent_path }}\\ActionSite.afxm'
