---
# handlers file for ansible-bigfix
- name: restart bigfix service (redhat)
  service:
    name: besclient
    state: restarted
  when: ansible_os_family = 'RedHat'

- name: restart bigfix service (windows)
  win_service:
    name: besclient
    state: restarted
  when: ansible_os_family = 'Windows'
